frontend/urls.py
from django.urls import path
from frontend import views

app_name = 'frontend'

urlpatterns = [
    path('about-page/', views.about, name='about'),
    path('service-page/', views.service, name='service'),
    path('support-page/', views.support, name='support'),
    path('hire-page/', views.hire, name='hire'),
    path('career-page/', views.career, name='career'),
    path('blog-page/', views.blog, name='blog'),
    path('privacy-page/', views.privacy, name='privacy'),
    path('terms-page/', views.terms, name='terms'),
    path('post-page/<int:pk>/', views.blog_details, name='blog_details'),
    path('search-page/', views.search, name='search'),
]

trans_ride/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from frontend import views
from django.urls import path, include
from filebrowser.sites import site


urlpatterns = [
    path('', views.Home.as_view(), name='index'),
    path('pages/', include('frontend.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/filebrowser/', site.urls),
    path('search/', views.search, name='search'),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root =settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/forms.py
from django import forms
from frontend.models import *
from django.core import validators
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
   

   
class DriverForm(forms.ModelForm):

    class Meta():
        model = Driver
        fields = "__all__"
   
        
        widgets = {
            'pst_firstname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter FirstName'}), 
            'pst_lastname':  forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter LasttName'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter PhoneNumber'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '@gmail.com'}),
            'state': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'home': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Home Address'}),
            'driver': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your Driver License No'}),
            'nin': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter NIN Number'}),
           
            
        }

class SupportForm(forms.ModelForm):

    class Meta():
        model = Support
        fields = "__all__"
       
       
        
        widgets = {
            'pst_firstname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter FirstName'}), 
            'pst_lastname':  forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter LasttName'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter PhoneNumber'}),
            'date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'DD:MM:YY  h:m'}),
            'pickoff': forms.TextInput(attrs={'class': 'form-control'}),
            'dropoff': forms.TextInput(attrs={'class': 'form-control'}),
            'drop_time': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'DD:MM:YY  h:m'}),
            'bus_no': forms.TextInput(attrs={'class': 'form-control'}),
            
        }

   
class HireForm(forms.ModelForm):

    class Meta():
        model = Hire
        
        fields = "__all__"
        
        widgets = {
            'pst_firstname':forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter FirstName'}), 
            'pst_lastname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter LasttName'}),
            'from_where' :forms.TextInput(attrs={'class': 'form-control'}),
            'to_where' :forms.TextInput(attrs={'class':'form-control'}),
            'phone':forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter PhoneNumber'}),
            'email':forms.TextInput(attrs={'class': 'form-control', 'placeholder': '@gmail.com'}),
            'passng':forms.NumberInput(attrs={'class' :'form-control'}),
            'da_ti': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'DD:MM:YY  h:m'}),
                   
            
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body','website')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Name'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Email'}),
            'website': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Website'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Type here'}),
            
        }

frontend/views.py
from multiprocessing import get_context
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse

from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
import sys
from frontend.forms import *
from frontend.models import *
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from django.conf import settings
from django.contrib import messages
from django.db.models import Count, Q

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import(
    ListView, DetailView,
    CreateView, FormView,
    TemplateView, View
)




class Home(TemplateView):
    template_name = 'frontend/index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['four'] = FourApp.objects.all()
        
        
       
        return context
       

def about(request):
    team=Team.objects.all()
    about =About.objects.all()
    return render(request, 'frontend/about.html', {'tem': team, 'abt' : about})

def service(request):
    form = DriverForm()
    if request.method == 'POST':
        form = DriverForm(request.POST)
        if form.is_valid():
            form = form.save()
            messages.success(request, 'Your form have been submited, Thanks for choosing Transtura')
    return render(request, 'frontend/service.html', {'form': form})

def support(request):
    support = Support2.objects.all()
    
    support_form = SupportForm()
    if request.method == 'POST':
        support_form = SupportForm(request.POST)
        if support_form.is_valid():
            support_form = support_form.save()
            messages.success(request, 'Ynks for choosing Transtura')
    return render(request, 'frontend/support.html', {'support_form':support_form, 'support' : support})



def hire(request):
    hire_form = HireForm()
    if request.method == 'POST':
        hire_form = HireForm(request.POST)
        if hire_form.is_valid():
            hire_form = hire_form.save()
            messages.success(request, 'You have requested for a Bus.Our Team Will Reach Out To You Within The Next 3hrs')
    return render(request, 'frontend/hire.html',{'hire_form':hire_form})

def career(request):
    car = Career.objects.all()
    return render(request, 'frontend/career.html', {'car' : car})

def blog(request):
    blog_post =  Blog.objects.order_by('-created')
    count_post = Blog.objects.filter().count()    
    most_recent = Blog.objects.order_by('created')[:4]
    paginated_filter = Paginator(blog_post, 6)
    page_number = request.GET.get('page')
    comments = Comment.objects.filter()
    person_page_obj = paginated_filter.get_page(page_number)

    context = {
        'person_page_obj': blog_post, 
        'most_recent': most_recent,
        'counts': count_post,
        'comm':comments
    }
    context['person_page_obj'] = person_page_obj  
    

    return render(request, 'frontend/blog-home.html', context)

def blog_details(request,pk):
    single_post = get_object_or_404(Blog,pk=pk)
    comments = Comment.objects.filter(post=pk).order_by('-created_on')
    most_recent = Blog.objects.order_by('created')[:4]
    
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False) 
            comment.post = single_post
            comment.save()
           
            return redirect('frontend:blog_details',pk=single_post.pk)
    else:
        form = CommentForm()     

    return render(request, 'frontend/blog-details.html',{
        
        'form':form,
        'sipst':single_post, 
        'comm': comments,
        'most_recent':most_recent
    
      
        })

def search(request):
    queryset = Blog.objects.all()
    query = request.GET.get('q')
    most_recent = Blog.objects.order_by('created')[:6]
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query)
        ).distinct()
    context = {
        'queryset': queryset,
        'most_recent':most_recent
    
        
    }
    return render(request, 'frontend/search_results.html', context)


def privacy(request):
    privacy=Privacy.objects.all()
    return render(request, 'frontend/privacy.html',{'privacy':privacy})

def terms(request):
    terms=Privacy.objects.all()
    return render(request, 'frontend/terms.html',{'terms':terms})

templates/frontend/base.html
{% load static %}
{% load fontawesome_5 %}
	<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="../../static/frontend/img/fg.png">
		<!-- Author Meta -->
		<meta name="author" content="colorlib">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		{% fontawesome_5_static %}
		<title>
			{% block title%}

			{% endblock%}
		</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="{% static 'frontend/css/linearicons.css' %}">
			<link rel="stylesheet" href="../../static/frontend/lib/css/font-awesome.min.css">
			<link rel="stylesheet" href="../../static/frontend/css/font-awesome.min.css">
			<link rel="stylesheet" href="{% static 'frontend/css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static 'frontend/css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static 'frontend/css/nice-select.css' %}">							
			<link rel="stylesheet" href="{% static 'frontend/css/animate.min.css' %}">
			<link rel="stylesheet" href="{% static 'frontend/css/jquery-ui.css' %}">			
			<link rel="stylesheet" href="{% static 'frontend/css/main.css' %}">
			<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
			<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
			<link rel="stylesheet" href="{% static 'frontend/css/custom.css' %}">
   

			<!-- Font Awesome -->
			

			<!-- Moment.js -->
			<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

			<!-- Tempus Dominus Bootstrap 4 -->
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
			<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
		</head>
		<body>	
			  <header id="header">
		  		<div class="header-top">
				</div>
			    <div class="container-fluid main-menu">
			    	<div class="row align-items-center justify-content-between d-flex">
			    		<a href="{%url 'index' %}"><img src="../../static/frontend/img/cropped-Logo_all-whiteYellow--145x24.png" alt="" title="" /></a>		
						<nav id="nav-menu-container">
							<ul class="nav-menu">
							  <li class="menu-active"><a href="{%url 'index' %}">Home</a></li>
							  <li><a href="{%url 'frontend:about' %}">About</a></li>
							  <li><a href="{%url 'frontend:service' %}">Drive With Us</a></li>
							  <li><a href="{%url 'frontend:support' %}">Support</a></li>
							  <li><a href="{%url 'frontend:hire' %}">Hire a bus</a></li>
							  <li class="menu-has-children"><a href="{%url 'frontend:blog' %}">Blog</a>
							</li>
							 						  			          	          
							  <li><a href="{%url 'frontend:career' %}">Career</a></li>
							  <li> <button class="btn btn-warning " style="padding: 3%; background-color: #f9d700;;">
								<a href="" >Download App</a>
							  </button>
							 
							  </li>
							</ul>
						</nav><!-- #nav-menu-container -->		
			    	</div>
			    </div>
			  </header><!-- #header -->

			  {% block content%}

			  {% endblock%}
			
			<!-- start footer Area -->		
			<footer class="footer-area text-center" style="background-color: rgb(19, 19, 19); padding-top: 5%; padding-bottom: 5%;">
				<div class="container">
					<div class="row">
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<img src="../../static/frontend/img/cropped-Logo_all-whiteYellow--145x24.png" class="img-fluid" alt="">
								
								<ul class="mt-30" >
									<li>294 Borno Way, Yaba, Lagos.
										support@transtura.com</li>
										<br>
									<li>07068330661, 08166499271</li>
									
								</ul>								
							</div>
						</div>
						
						<div class="col-lg-2 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6 style="color:  #f9d700;;">Who We Are</h6>
								<ul>
									<li><a href="{%url 'frontend:about' %}">About</a></li>
									<li><a href="{%url 'frontend:service' %}">Drive With Us</a></li>
									
								</ul>								
							</div>
						</div>	
						<div class="col-lg-2 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6 style="color:  #f9d700;;">Company</h6>
								<ul>
									<li><a href="#">FAQs</a></li>
									<li><a href="{%url 'frontend:support' %}">Support</a></li>
									<li class="menu-has-children"><a href="{%url 'frontend:blog' %}">Blog</a>
									
								</ul>								
							</div>
						</div>												
						<div class="col-lg-2 col-md-6 col-sm-6 social-widget" >
							<div class="single-footer-widget">
								<h6 style="color:  #f9d700;;">Follow Us</h6>
								
								<div class="footer-social d-flex align-items-center" style="margin-left: 30%;">
									<a href="#"><i class="fa fa-facebook" ></i></a>
									<a href="#"><i class="fa fa-twitter"></i></a>
									<a href="#"><i class="fa fa-dribbble"></i></a>
									<a href="#"><i class="fa fa-behance"></i></a>
								</div>
							</div>
						</div>							
						<div class="col-lg-3 col-md-12 col-sm-6">
							<div class="single-footer-widget">
								<h6 style="color:  #f9d700;;">Legal</h6>
								<ul>
									<li><a href="{%url 'frontend:privacy' %}">Privacy Policy</a></li>
									<li class="menu-has-children"><a href="{%url 'frontend:terms' %}">Terms & Conditions</a>
									
								</ul>								
							</div>
						</div>	
																	
					</div>
				</div>
				<img class="footer-bottom" src="img/footer-bottom.png" alt="">
			</footer>	
			<!-- End footer Area -->	

			<script src="{% static 'frontend/js/vendor/jquery-2.2.4.min.js' %}"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
			<script src="{% static 'frontend/js/vendor/bootstrap.min.js' %}"></script>			
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
  			<script src="{% static 'frontend/js/easing.min.js' %}"></script>			
			<script src="{% static 'frontend/js/hoverIntent.js' %}"></script>
			<script src="{% static 'frontend/js/superfish.min.js' %}"></script>	
			<script src="{% static 'frontend/js/jquery.ajaxchimp.min.js' %}"></script>
			<script src="{% static 'frontend/js/jquery.magnific-popup.min.js' %}"></script>	
 			<script src="{% static 'frontend/js/jquery-ui.js' %}"></script>								
			<script src="{% static 'frontend/js/jquery.nice-select.min.js' %}"></script>							
			<script src="{% static 'frontend/js/mail-script.js' %}"></script>	
			<script src="{% static 'frontend/js/main.js' %}"></script>	
		</body>
	</html>

templates/frontend/index.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title%}
Home
{% endblock %}

{% block content %}
			<!-- start banner Area -->
			<section class="banner-area relative mt-20"  id="home">
				<div class="overlay overlay-bg"></div>	
				<div class="container">
					<div class="row fullscreen d-flex align-items-center justify-content-between">
						<div class="banner-content col-lg-6 col-md-6  ">
							
							<h1 class="ml-50" style="color: black; font-size: 3rem; font-family: 'Montserrat', sans-serif; font-weight: 900;">
								Move around the city daily with Transtura			
							</h1>
							<p class="ml-50" style="color: black;  font-family: 'Montserrat', sans-serif; font-weight: 900;">Affordable, Smart, Safe and Comfortable Intracity Ride</p>
						</div>
					
						<div class="col-lg-6  col-md-6 ">
							<img src="../../static/frontend/img/trans_bus.png" class="img-fluid mt-50 col-sm-10" style="" alt="">
							<br>
							<div class="col-md-12 text-center mt-50">
								<a href="#" class="btn btn-outline-dark text-uppercase">Call for Transtura</a>
							</div>
							
							
							

							
							
						</div>		
						<div class="row mt-30 mb-30 mx-auto pic">
	
							<div class="col-lg-6 col-sm-5">
							<img src="../../static/frontend/img/google-play-badge-logo-png-transparent-300x104.png" class="col-lg-12 mb-50" alt="">
							</div>	
								
							<div class=" col-lg-6 col-sm-5 " >
								<img src="../../static/frontend/img/apple-app-store-logo-300x104.png" class="col-lg-12 " alt="">
							</div>
						</div>				
					</div>
					
				</div>			
						
			</section>
			<!-- End banner Area -->	
			<br><br><br>

				<!-- Start home-about Area -->
				<section class="home-about-area section-gap">
					<div class="container">
						<div class="text-center">
							<h1 style="color: black; font-size: 50px; font-family: 'Montserrat', sans-serif;">Transtura</h1>
							<br>
							<p style="color: black; line-height: 30px; font-size: 15px; font-family: 'Montserrat', sans-serif;">
								Transtura is a public transportation management company that provides comfortable, 
								convenient, reliable, safe, and affordable on demand bus ride sharing service. Our
								 smart ride hailing service enables people to commute within their cities at the 
								 cheapest price using our tech-driven solutions.
							</p>
							 <a href="{%url 'frontend:about' %}"><button class="btn btn-outline-warning btn-lg" style=" font-family: 'Montserrat', sans-serif;">Learn More</button></a>
						</div>
					</div>	
				</section>
				<!-- End home-about Area -->
			<!-- Start home-about Area -->
			<section class="home-about-area ">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-6 about-left">
							<img class="img-fluid" src="../../static/frontend/img/trans_bus.png" alt="">
						</div>
						<div class="col-lg-6 about-right">
							<h1>A smart way to commute in Lagos</h1>
							
							<p>		
								Whether you’re looking for a smart way to commute, or to earn a living, we’ve got you covered.						
							</p>
							
							
													
									<div class="row mx">
										<div class="col-lg-6 col-md-6 col-sm-12 mt-50">
											<div class="single-review5">
												<a class=""  href="#">Ride with Transtura</a>

											</div>
										</div>	
										<div class="col-lg-6 col-md-6 col-sm-12 mt-50">
											<div class="single-review5 mx-auto">
												
												<a class=" " href="#">Ride with Transtura</a>
											</div>
										</div>	
																																						
									</div>
							
						</div>
					</div>
				</div>	
			</section>
			<!-- End home-about Area -->
			
		

			<br><br><br>
				<!-- Start reviews Area -->
				<section class="reviews-area">
					<div class="container">
						<div class="section-title">
							<h1 style="text-align: center; font-weight: 800; font-family: 'Montserrat', sans-serif;">What is Driving Us</h1>
							
						</div>					
						<div class="row">
							<div class="col-lg-4 col-md-6">
								<div class="single-review3">
									<span><i class="fa fa-ambulance" style="text-align: left; font-size: 50px; color: black;"></i></span>
									<h4 style=" font-family: 'Montserrat', sans-serif;">Safety for everyone </h4>
									<p>
										We are redefining public travel experience by ensuring that you are safe throughout your commuting time with us using technology and automations.
									</p>
									
								</div>
							</div>	
							<div class="col-lg-4 col-md-6">
								<div class="single-review4">
									<span><i class="fa fa-calendar-o" style="text-align: left; font-size: 50px;"></i></span>
									<h4 style=" font-family: 'Montserrat', sans-serif;">Excellent shared commuting service </h4>
									<p>
										We provide you with hassle free and smart bus travel. You can book a ride and schedule a trip right from the comfort of your home. Our professional pilots and air-conditioned buses are available 24/7.
									</p>
									
								</div>
							</div>	
							<div class="col-lg-4 col-md-6">
								<div class="single-review3">
									<span><i class="fa fa-street-view" style="text-align: left; font-size: 50px; color: black;"></i></span>
									<h4 style=" font-family: 'Montserrat', sans-serif;">Connect people</h4>
									<p>
										A ride with us is an opportunity to meet new people in your community and build defining and important relationships.
									</p>
								</div>
							</div>	
							
																																						
						</div>
					</div>	
				</section>
				<!-- End reviews Area -->
				<hr  style="background-color: black; font-weight: bolder; width: 80%;">
				<br>
				<!-- Start reviews Area -->
				<section class="reviews-area">
					<div class="container">
										
						<div class="row">
							
							<div class=" offset-lg-2 col-lg-4 col-md-6">
								<div class="single-review4">
									<span><i class="fa fa-thumbs-up" style="text-align: left; font-size: 50px;"></i></span>
									<h4 style=" font-family: 'Montserrat', sans-serif;">Save the planet</h4>
									<p>
										By helping to reduce the number of cars on the road, we can save the planet and make it healthier than we met it.
									</p>
									
								</div>
							</div>	
							<div class="col-lg-4 col-md-6">
								<div class="single-review3">
									<span><i class="fa fa-credit-card" style="text-align: left; font-size: 50px; color: black;"></i></span>
									<h4 style=" font-family: 'Montserrat', sans-serif;">Affordable Ride</h4>
									<p>
										We provide an on demand buspool trip at the cheapest price you can ever imagined with
										 professional drivers and air-conditioned buses.
									</p>
									
								</div>
							</div>	
																																						
						</div>
					</div>	
				</section>
				<!-- End reviews Area -->
			
		
			<br><br><br>
		
							
			<!-- Start home-calltoaction Area -->
			<section class="home-calltoaction-area relative mt-20 section-gap">
				<div class="container">
					
					<div class="row align-items-center">
						<div class="col-lg-8">
							<h1 style="font-family: 'Montserrat', sans-serif; font-weight: 700; ">Affordable. Smart. <br> Safe. Comfortable.</h1>
							<p style="color: black; font-weight: 500;">
								For maximum comfort while also communicating smartly, ride with us and <br> experience Transtura magic
							</p>
						</div>
						<div class="col-lg-4 btn-left">
							<img src="../../static/frontend/img/mockk.png" class="img-fluid"  alt="">
						</div>
						<div class="row mt-30 mb-30 mx-auto pic">
	
							<div class="col-lg-6 col-sm-5">
							<img src="../../static/frontend/img/google-play-badge-logo-png-transparent-300x104.png" class="col-lg-12 mb-50" alt="">
							</div>	
								
							<div class=" col-lg-6 col-sm-5 " >
								<img src="../../static/frontend/img/apple-app-store-logo-300x104.png" class="col-lg-12 " alt="">
							</div>
						</div>		
					</div>
				</div>	
			</section>
			<!-- End home-calltoaction Area -->
			<br>
				<!-- Start services Area -->
				<section class="services-area pb-120">
					<div class="container-fluid">
						<div class="section-title text-center">
							<h4 >Your Ride</h4>
							<h1>Four Options in One App</h1>
							
						</div>
						<div class="row" style="background-image: linear-gradient(
							180deg, #FFFFFF 0%, #9A9A9A 100%);" >
							{% if four %}
							{% for f in four%}
							<div class="col-lg-5 col-md-6  single-service1 mx-auto ">
								<h4 style="font-size:40px;  font-family: 'Montserrat', sans-serif;">{{ f.title }}</h4>
								<p class="text-left" style="color: rgb(0, 0, 0); font-weight: 500; font-size: 20px;">
									{{ f.content }}
								</p>
								<br>
								<img src="{{ f.post_img }}" class="img-fluid"  alt="">
							</div>
							{% endfor %}
							{% endif %}
							
																		
						</div>	
					</div>	
				</section>
				<!-- End services Area -->
				<br><br><br>
			<!-- Start home-calltoaction Area -->
			<section class="home-calltoaction-area1 relative" style="background-color: black;">
				<div class="container">
					<div class="overlay overlay-bg"></div>
					<div class="row align-items-center section-gap">
						<div class="col-lg-8">
							<h1 style="font-weight: bold; color: rgb(255, 255, 255); font-size: 60px;">Short trips that promise comfort and convenience</h1>
						
						</div>
						<div class="col-lg-4 btn-left">
							<img src="../../static/frontend/img/moc.png" class="img-fluid"  alt="">
						</div>
						
					</div>
				</div>	
			</section>
			<!-- End home-calltoaction Area -->
			
		
			
{% endblock %}